### ISSUE TITLE
Memory Crash

### ISSUE THREAD

**Issue by terrarazerofficial** [derrekr/srb2_3ds#16]
Hello derrek6, sorry to bother you, but I am getting a frequent issue I see no one else having, or at least cannot find anything about it, after thz I always get the error: “out of memory allocating 419412” or along those lines, I’d just like to wonder what I can do to avoid this?

**Comment by derrekr** [comment]
Hi @terrarazerofficial, are you running srb2_3ds on a New3DS and are you using any mods?

**Comment by terrarazerofficial** [comment]
At first I thought that might be the case as well, however, I deleted my mods and came up with the same issue

**Comment by terrarazerofficial** [comment]
However, I do see a frequent error known as: “I_mkdir() failed!” I don’t know if that has anything to do with it, but I thought I should add that

**Comment by terrarazerofficial** [comment]
I managed to get to a point of being in deep sea zone 1 with 5 emeralds, although just barely as it crashed the first time I even got the fifth one

**Comment by derrekr** [comment]
I wonder if that's due to an out of memory condition (causing a NULL pointer dereference) or something else.
In my tests, oom only appeared in the game's final boss fight (which I fixed though). On the other hand, I haven't tested the emeralds stuff.
As a first measure, I would try simply reinstalling the game and see if that fixes it (delete and download everything again, just keep the savegame).

**Comment by terrarazerofficial** [comment]
Ok, I'll give it a try, thanks for the idea

**Comment by terrarazerofficial** [comment]
I'm happy to report that after redownloading everything, not only am I am castle eggman zone, but I have all 7 chaos emeralds, thank you

**Comment by derrekr** [comment]
Awesome!
