### ISSUE TITLE
Laggy Special Stages & Visually Glitched Acts

### ISSUE THREAD

**Issue by Axonic3D** [derrekr/srb2_3ds#7]
Greetings derrekr.
Before I report some of the bugs I've discovered on my own playthrough, I'd like to give you all my gratitude towards making this port a reality. For so long I have been wishing for a 3DS port and you've made my dream come true! Thank you so much!

*ahem* Now, for as smooth and slick that this port is, I've discovered a couple of bugs which might make the game near impossible to complete. Starting off, the special stages "Flooded Cove Zone" and "Magma Caves Zone" tend to lag often, but none more so than the former (FCZ) which is an absolute lagfest from start to finish. Thankfully, they're still beatable. On the other hand, Techno Hill Zone Act 2 and Castle Eggman Zone Act 1 are almost entirely unbeatable unless if memorized due to some odd graphical glitches that brings the background forward, covering everything else (minus the HUD).

I care about this port and wouldn't want to see it left in a state where it's impossible to beat, so I'll do what I can to help. If you require photos/screenshots, I'll gladly share them.

Sincerely,
Axonic3D

P.S.: I don't know if it's worth talking about bugs in WADs, especially since it's likely that most problems on them would be up for their respective creators to fix, but I'd like to mention that a similar graphical glitch as the previously mentioned one happens in SRB2 Heroes' Grand Metropolis stage, rendering it imposible to complete.

**Comment by derrekr** [comment]
Hi Axonic3D,
good to hear you like my port :)
The "special stages" you mentioned are NiGHTS ( https://wiki.srb2.org/wiki/NiGHTS ). It's a known issue those levels tend to be very laggy. I am not sure what's the root cause, but it's probably related to SRB2's scene rendering. Personally, I think it's a bit unfortunate, but not being able to clear all NiGHTs probably isn't that severe imho.

Regarding THZ2 and CEZ1, I am not aware of any lag issues that would make those zones nearly impossible to beat.
Are you sure you're on the latest version (v1.1.3 at the time of writing) and are you playing this port on a New3DS? Have you changed anything in the video settings/config file? What is the estimated average FPS value in THZ2? You can enable showing FPS in the video settings.
Also, it would be helpful if you could describe how to trigger that odd graphical glitch.

Some WADs might need adjustments to make them run flawlessly on New3DS, especially with regards to performance (the CPU is still a bottleneck). However, it sounds like the graphical glitch could be an issue specific to this port.

Kind regards,
derrek

**Comment by Axonic3D** [comment]
Hello again derrekr.

     The case of the special stages/NiGHTS stages is unfortunate, but they're still beatable so I don't think there's much concern there. Players such as myself will just have to bear the lag, and I don't think it's that big of a problem, as I just stated.

The issue in THZ 2 and CEZ 1 isn't lag, far from it. Actually, I just discovered a solution to it: disabling skyboxes. After I did that, the skybox/background wasn't layered over the actual gameplay and I could see where I was going. I also played some more of CEZ 2 and not only is the lag just as bad as you mentioned in the README file, but the game can panic and crash probably due to that same reason (only happened to me once though).

Indeed, I am using the latest version of the port with the latest version of the game on my New 3DS XL. I hadn't really changed the config until a couple hours ago just to disable the skybox. My "default" resolution is around 1200 × 800, 16 bits.

One thing I would suggest (maybe added into the README as instructions or as its own file for the port) is add some form of "recommended settings" for a better playing experience. Stuff like "disable skyboxes," "set software fog to Off" and a proper resolution are a few good examples.

I'm glad to help with this port however I can. If you need further assistance, I'll do what I can to offer that which you require.

Sincerely,
Axel J.

**Comment by derrekr** [comment]
Hi again,

maybe I am wrong, but it sounds like you have copied the config file from your computer's SRB2 installation. When srb2_3ds is launched and cannot find any config file (fresh installation), it tries to create one itself using 3DS-specific settings. So usually skyboxes and SW fog are disabled for performance reasons.
Maybe the port should force-set certain settings to avoid the problem you encountered.
Adding a "recommended settings" section in the README seems like a good idea.

> I'm glad to help with this port however I can. If you need further assistance, I'll do what I can to offer that which you require.

Feel free to contribute to srb2_3ds's source.
Making WADs more 3DS friendly is appreciated as well.

Kind regards,
derrek

**Comment by Axonic3D** [comment]
Hello derrekr,

Yeah, that's actually what I did. I just erased the existing one and it did in fact create a new config with the 3DS specific settings. I greatly appreciate that!

Huh, a reason to start learning how to code and whatnot. I actually know very little on how any of that stuff works, so alas I don't think I can help there. The most I could do is report bugs/issues. Maybe with the ability to contribute to the port's source I could change the config so it has the best settings? Not that I'm going to, even if I could.

Sincerely,
Axonic3D
